### ISSUE TITLE
support more keywords

### ISSUE THREAD

**Issue by sunshaoce** [jakoberzar/vscode-llvm-tablegen#2]
such as `true`. And operators such as `!cast`, `!add`. Defined in https://llvm.org/docs/TableGen/ProgRef.html#id7

**Comment by jakoberzar** [comment]
Hi, thanks for creating an issue!
I'm currently occupied with other things, so I will look into this later. However, if you would like to add them yourself, please feel free to do so, pull requests are welcome!

**Comment by emosy** [comment]
I addressed this in my PR #3
